/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.upnvj.screen;

import javax.swing.JOptionPane;

/**
 *
 * @author DAPIT
 */
public class Screen_SignUp extends javax.swing.JFrame {

    /**
     * Creates new form Screen_SignUp
     */
    public Screen_SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_design = new javax.swing.JPanel();
        icon_mBanking = new javax.swing.JLabel();
        panel_main = new javax.swing.JPanel();
        panel_signUp = new javax.swing.JPanel();
        label_signUp = new javax.swing.JLabel();
        panel_input = new javax.swing.JPanel();
        label_fullName = new javax.swing.JLabel();
        field_fullName = new javax.swing.JTextField();
        label_cardNum = new javax.swing.JLabel();
        field_cardNum = new javax.swing.JTextField();
        label_exDate = new javax.swing.JLabel();
        field_exDate = new javax.swing.JTextField();
        label_accNum = new javax.swing.JLabel();
        field_accNum = new javax.swing.JTextField();
        label_PIN = new javax.swing.JLabel();
        field_PIN = new javax.swing.JTextField();
        button_signUp = new javax.swing.JButton();
        panel_signIn = new javax.swing.JPanel();
        label_alreadyHave = new javax.swing.JLabel();
        button_signIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple M-Banking");
        setMaximumSize(new java.awt.Dimension(840, 480));
        setMinimumSize(new java.awt.Dimension(840, 480));
        setResizable(false);

        panel_design.setBackground(new java.awt.Color(109, 152, 134));
        panel_design.setPreferredSize(new java.awt.Dimension(510, 480));
        panel_design.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 60));

        icon_mBanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("../icons/icon_ewallet.png"))); // NOI18N
        panel_design.add(icon_mBanking);

        getContentPane().add(panel_design, java.awt.BorderLayout.CENTER);

        panel_main.setBackground(new java.awt.Color(57, 62, 70));
        panel_main.setPreferredSize(new java.awt.Dimension(330, 480));

        panel_signUp.setBackground(new java.awt.Color(57, 62, 70));
        panel_signUp.setPreferredSize(new java.awt.Dimension(330, 50));
        panel_signUp.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        label_signUp.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        label_signUp.setForeground(new java.awt.Color(255, 255, 255));
        label_signUp.setText("Create a new account");
        panel_signUp.add(label_signUp);

        panel_main.add(panel_signUp);

        panel_input.setBackground(new java.awt.Color(57, 62, 70));
        panel_input.setPreferredSize(new java.awt.Dimension(330, 370));

        label_fullName.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        label_fullName.setForeground(new java.awt.Color(255, 255, 255));
        label_fullName.setText("Full Name");

        field_fullName.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        field_fullName.setPreferredSize(new java.awt.Dimension(230, 30));
        field_fullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_fullNameActionPerformed(evt);
            }
        });

        label_cardNum.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        label_cardNum.setForeground(new java.awt.Color(255, 255, 255));
        label_cardNum.setText("Card Number");

        field_cardNum.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        field_cardNum.setPreferredSize(new java.awt.Dimension(230, 30));
        field_cardNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_cardNumActionPerformed(evt);
            }
        });

        label_exDate.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        label_exDate.setForeground(new java.awt.Color(255, 255, 255));
        label_exDate.setText("Expired Date");

        field_exDate.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        field_exDate.setPreferredSize(new java.awt.Dimension(230, 30));
        field_exDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_exDateActionPerformed(evt);
            }
        });

        label_accNum.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        label_accNum.setForeground(new java.awt.Color(255, 255, 255));
        label_accNum.setText("Account Number");

        field_accNum.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        field_accNum.setPreferredSize(new java.awt.Dimension(230, 30));
        field_accNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_accNumActionPerformed(evt);
            }
        });

        label_PIN.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        label_PIN.setForeground(new java.awt.Color(255, 255, 255));
        label_PIN.setText("PIN");

        field_PIN.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        field_PIN.setPreferredSize(new java.awt.Dimension(230, 30));
        field_PIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_PINActionPerformed(evt);
            }
        });

        button_signUp.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        button_signUp.setText("Sign Up");
        button_signUp.setPreferredSize(new java.awt.Dimension(230, 30));
        button_signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_signUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_inputLayout = new javax.swing.GroupLayout(panel_input);
        panel_input.setLayout(panel_inputLayout);
        panel_inputLayout.setHorizontalGroup(
            panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inputLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(button_signUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field_fullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_fullName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_cardNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_cardNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_exDate, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_exDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_accNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_accNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_PIN, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_PIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        panel_inputLayout.setVerticalGroup(
            panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_inputLayout.createSequentialGroup()
                .addComponent(label_fullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_fullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_cardNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_cardNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_exDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_exDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_accNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_accNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_PIN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(button_signUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_main.add(panel_input);

        panel_signIn.setBackground(new java.awt.Color(57, 62, 70));
        panel_signIn.setPreferredSize(new java.awt.Dimension(330, 40));
        panel_signIn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        label_alreadyHave.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        label_alreadyHave.setForeground(new java.awt.Color(255, 255, 255));
        label_alreadyHave.setText("Already have an account?");
        panel_signIn.add(label_alreadyHave);

        button_signIn.setBackground(new java.awt.Color(57, 62, 70));
        button_signIn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        button_signIn.setForeground(new java.awt.Color(255, 255, 255));
        button_signIn.setText("Sign in");
        button_signIn.setBorder(null);
        button_signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_signInActionPerformed(evt);
            }
        });
        panel_signIn.add(button_signIn);

        panel_main.add(panel_signIn);

        getContentPane().add(panel_main, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_fullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_fullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_fullNameActionPerformed

    private void button_signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_signUpActionPerformed
        // TODO add your handling code here:
        Screen_Dashboard dashboard = new Screen_Dashboard();
        dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_button_signUpActionPerformed

    private void field_cardNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_cardNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_cardNumActionPerformed

    private void field_exDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_exDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_exDateActionPerformed

    private void field_accNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_accNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_accNumActionPerformed

    private void field_PINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_PINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_PINActionPerformed

    private void button_signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_signInActionPerformed
        // TODO add your handling code here:
        Screen_SignIn signin = new Screen_SignIn();
        signin.setVisible(true);
        dispose();
    }//GEN-LAST:event_button_signInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen_SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_signIn;
    private javax.swing.JButton button_signUp;
    private javax.swing.JTextField field_PIN;
    private javax.swing.JTextField field_accNum;
    private javax.swing.JTextField field_cardNum;
    private javax.swing.JTextField field_exDate;
    private javax.swing.JTextField field_fullName;
    private javax.swing.JLabel icon_mBanking;
    private javax.swing.JLabel label_PIN;
    private javax.swing.JLabel label_accNum;
    private javax.swing.JLabel label_alreadyHave;
    private javax.swing.JLabel label_cardNum;
    private javax.swing.JLabel label_exDate;
    private javax.swing.JLabel label_fullName;
    private javax.swing.JLabel label_signUp;
    private javax.swing.JPanel panel_design;
    private javax.swing.JPanel panel_input;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_signIn;
    private javax.swing.JPanel panel_signUp;
    // End of variables declaration//GEN-END:variables
}
