/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.upnvj.screen;

import javax.swing.JOptionPane;
import com.upnvj.Program;

/**
 *
 * @author DAPIT
 */
public class Screen_SignIn extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */

    Program program;
    public Screen_SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_design = new javax.swing.JPanel();
        icon_mBanking = new javax.swing.JLabel();
        panel_main = new javax.swing.JPanel();
        panel_signIn = new javax.swing.JPanel();
        label_signIn = new javax.swing.JLabel();
        panel_input = new javax.swing.JPanel();
        label_cardNum = new javax.swing.JLabel();
        field_cardNum = new javax.swing.JTextField();
        label_PIN = new javax.swing.JLabel();
        button_signIn = new javax.swing.JButton();
        field_PIN = new javax.swing.JPasswordField();
        panel_signUp = new javax.swing.JPanel();
        label_dontHave = new javax.swing.JLabel();
        button_signup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple M-Banking");
        setMinimumSize(new java.awt.Dimension(840, 480));
        setResizable(false);

        panel_design.setBackground(new java.awt.Color(109, 152, 134));
        panel_design.setMaximumSize(new java.awt.Dimension(510, 480));
        panel_design.setPreferredSize(new java.awt.Dimension(510, 480));
        panel_design.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 60));

        icon_mBanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("../icons/icon_ewallet.png"))); // NOI18N
        panel_design.add(icon_mBanking);

        getContentPane().add(panel_design, java.awt.BorderLayout.CENTER);

        panel_main.setBackground(new java.awt.Color(57, 62, 70));
        panel_main.setPreferredSize(new java.awt.Dimension(330, 480));

        panel_signIn.setBackground(new java.awt.Color(57, 62, 70));
        panel_signIn.setPreferredSize(new java.awt.Dimension(330, 130));
        panel_signIn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 80));

        label_signIn.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        label_signIn.setForeground(new java.awt.Color(255, 255, 255));
        label_signIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_signIn.setText("Sign in to your account");
        label_signIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel_signIn.add(label_signIn);

        panel_main.add(panel_signIn);

        panel_input.setBackground(new java.awt.Color(57, 62, 70));
        panel_input.setPreferredSize(new java.awt.Dimension(330, 220));

        label_cardNum.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        label_cardNum.setForeground(new java.awt.Color(255, 255, 255));
        label_cardNum.setText("Card Number");

        field_cardNum.setPreferredSize(new java.awt.Dimension(230, 30));

        label_PIN.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        label_PIN.setForeground(new java.awt.Color(255, 255, 255));
        label_PIN.setText("PIN");

        button_signIn.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        button_signIn.setText("Sign in");
        button_signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_signInActionPerformed(evt);
            }
        });

        field_PIN.setPreferredSize(new java.awt.Dimension(230, 30));

        javax.swing.GroupLayout panel_inputLayout = new javax.swing.GroupLayout(panel_input);
        panel_input.setLayout(panel_inputLayout);
        panel_inputLayout.setHorizontalGroup(
            panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_inputLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label_cardNum)
                        .addComponent(field_cardNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_PIN)
                        .addComponent(button_signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panel_inputLayout.setVerticalGroup(
            panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_inputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_cardNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_cardNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_PIN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(button_signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        panel_main.add(panel_input);

        panel_signUp.setBackground(new java.awt.Color(57, 62, 70));
        panel_signUp.setPreferredSize(new java.awt.Dimension(330, 40));

        label_dontHave.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        label_dontHave.setForeground(new java.awt.Color(255, 255, 255));
        label_dontHave.setText("Don't have an account?");
        panel_signUp.add(label_dontHave);

        button_signup.setBackground(new java.awt.Color(57, 62, 70));
        button_signup.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        button_signup.setForeground(new java.awt.Color(255, 255, 255));
        button_signup.setText("Sign up");
        button_signup.setBorder(null);
        button_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_signupActionPerformed(evt);
            }
        });
        panel_signUp.add(button_signup);

        panel_main.add(panel_signUp);

        getContentPane().add(panel_main, java.awt.BorderLayout.EAST);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_signInActionPerformed
        try {
            this.program = new Program();
            // long cardNum = Long.parseLong(field_cardNum.getText()) ;
            // int pin = Integer.parseInt(new String (field_PIN.getPassword()));
            long cardNum = 341241351673932L;
            int pin = 321321;
            int code = program.login(cardNum, pin);
            // System.out.println(program.getAccount());

            switch (code) {
                case 0:
                    Screen_Dashboard dashboard = new Screen_Dashboard();
                    dashboard.getDetails(program);
                    dashboard.setValue();
                    dashboard.setVisible(true);
                    dispose();
                    break;
                case 1:
                    JOptionPane.showMessageDialog(rootPane, 
                        "The card number or PIN you're trying to enter is incorrect!", 
                        "", 2);
                    break;
                case 2:
                    JOptionPane.showMessageDialog(rootPane, 
                        "Unexpected error", 
                        "", 2);
                    break;
                default:
                    break;
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, 
                "You need to enter all of the field in order to sign in!", 
                "", 2);
        }        
    }//GEN-LAST:event_button_signInActionPerformed

    private void button_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_signupActionPerformed
        Screen_SignUp signup = new Screen_SignUp();
        signup.setVisible(true);
        dispose();
    }//GEN-LAST:event_button_signupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen_SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen_SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_signIn;
    private javax.swing.JButton button_signup;
    private javax.swing.JPasswordField field_PIN;
    private javax.swing.JTextField field_cardNum;
    private javax.swing.JLabel icon_mBanking;
    private javax.swing.JLabel label_PIN;
    private javax.swing.JLabel label_cardNum;
    private javax.swing.JLabel label_dontHave;
    private javax.swing.JLabel label_signIn;
    private javax.swing.JPanel panel_design;
    private javax.swing.JPanel panel_input;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_signIn;
    private javax.swing.JPanel panel_signUp;
    // End of variables declaration//GEN-END:variables
}
